### ISSUE TITLE
add project.toml

### ISSUE THREAD

**Issue by floswald** [BenjaminBorn/HANK_BusinessCycleAndInequality#3]
hi guys

thanks for this, looks very good. just a quick pointer to improve reproducibility of this package substantially: add a `project.toml` file to the root of the repo. that will specify the exact package versions of all dependencies and aides installation substantially. e.g. I could just have typed `] instantiate ` to fetch all your dependencies automatically. it's easy to set up: https://julialang.github.io/Pkg.jl/v1/environments/

good job! :+1:

**Comment by BenjaminBorn** [comment]
Thanks Florian. You are absolutely right and this is on our agenda. It's also a good reason to finally look into all the new Pkg.jl stuff.

We are currently revising the paper and will clean and update the repository over the next month.

**Comment by BenjaminBorn** [comment]
Closed by #4. Thanks again for the suggestion.
